module.exports = {
      triage: {
            "_id"             :  "1",
            "email"             :  "triage@triage.com",
            "surname"           :  "Greg",
            "giveName"          :  "Sam",
            "dateOfBirthDay"    :  "26",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              :  "triage"
      },

      gp: {
            "_id"             :  "2",
            "email"             :  "gp@gp.com",
            "surname"           :  "Khor",
            "giveName"          :  "Ian",
            "dateOfBirthDay"    :  "30",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "gp",
            "doctorSurname"     : "Arrest",
            "doctorGivenName"   : "Cardiac",
            "doctorClinic"      : "Chest Pain Clinic",
            "doctorAddress"     : "123, Fake street, Melbourne",
            "doctorPostcode"    : "3000",
            
      },

      gp2: {
            "_id"             :  "3",
            "email"             :  "gp2@gp2.com",
            "surname"           :  "Loong",
            "giveName"          :  "Michael",
            "dateOfBirthDay"    :  "30",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "gp",
            "doctorSurname"     : "Ball",
            "doctorGivenName"   : "Crystall",
            "doctorClinic"      : "Magic Clinic",
            "doctorAddress"     : "123, Real street, Melbourne",
            "doctorPostcode"    : "3000",
      },

      psychiatrist: {
            "_id"             :  "4",
            "email"             :  "psy@psy.com",
            "surname"           :  "Chen",
            "giveName"          :  "Sharon",
            "dateOfBirthDay"    :  "18",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "psychiatrist",  
            "doctorSurname"     : "Sam",
            "doctorGivenName"   : "Greg",
            "doctorClinic"      : "Archilles Clinic",
            "doctorAddress"     : "123, Badminton street, Melbourne",
            "doctorPostcode"    : "3000",   
      },
      psychiatrist2: {
            "_id"             :  "5",
            "email"             :  "psy2@psy2.com",
            "surname"           :  "Ward",
            "giveName"          :  "Seb",
            "dateOfBirthDay"    :  "18",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "psychiatrist", 
            "doctorSurname"     : "Sara",
            "doctorGivenName"   : "Ng",
            "doctorClinic"      : "NG Technology",
            "doctorAddress"     : "123, Electronics street, Melbourne",
            "doctorPostcode"    : "3000",    
      }
}