module.exports = {
      triage: {
            "_id":                        1,
            "referralStatus":             "accepted",
            "patientSurname":             "Brady",
            "patientgivenName":           "Cardia",
            "patientGender":              "M",
            "patientBirthDay":            12,
            "patientBirthMonth":          9,
            "patientBirthYear":           1985,
            "patientAddress":             "120, Spencer Street, Melbourne",
            "patientPostcode":            "3000",
            "patientMedicare":            "12345678901",
            "patientContactNumber":       "0412345678",
            "doctorSurname":              "Arrest",
            "doctorGivenName":            "Cardiac",
            "doctorClinic":               "Chest Pain Clinic",
            "doctorAddress":              "123, Fake street, Melbourne",
            "doctorPostcode":             "3000",
            "doctorContactNumber":        "0412345679",
            "referralAppointmentDay":     12,
            "referralAppointmentMonth":   12,
            "referralAppointmentYear":    2017,
            "referralRequestedService":   "medicationReview",
            "referralReasonForReferral":  "He is crazy",
            "referralUrgent":             false,
            "referralRuralCode":          "RA3OuterRegional", 
            "referralAppointmentDate":    "12-12-2016",
            "referralAppointmentHour":    12,
            "referralAppointmentMinute":  30,
            "referralAppointmentPeriod":  "PM",
            "role":                       "admin",
            imgProfile:                   'https://openclipart.org/image/2400px/svg_to_png/225296/Red-Heart.png'
      },

      gp: {
            "_id":                        2,
            "referralStatus":             "accepted",
            "patientSurname":             "Ball",
            "patientgivenName":           "Crystall",
            "patientGender":              "M",
            "patientBirthDay":            12,
            "patientBirthMonth":          9,
            "patientBirthYear":           1985,
            "patientAddress":             "120, Spencer Street, Melbourne",
            "patientPostcode":            "3000",
            "patientMedicare":            "12345678901",
            "patientContactNumber":       "0412345678",
            "doctorSurname":              "Arrest",
            "doctorGivenName":            "Cardiac",
            "doctorClinic":               "Chest Pain Clinic",
            "doctorAddress":              "123, Fake street, Melbourne",
            "doctorPostcode":             "3000",
            "doctorContactNumber":        "0412345679",
            "referralAppointmentDay":     12,
            "referralAppointmentMonth":   12,
            "referralAppointmentYear":    2017,
            "referralRequestedService":   "medicationReview",
            "referralReasonForReferral":  "He is crazy",
            "referralUrgent":             false,
            "referralRuralCode":          "RA3OuterRegional", 
            "referralAppointmentDate":    "12-12-2016",
            "referralAppointmentHour":    12,
            "referralAppointmentMinute":  30,
            "referralAppointmentPeriod":  "PM",
            "role":                       "admin",
            imgProfile:                   'http://static8.comicvine.com/uploads/square_medium/11117/111171699/3921775-starlord2014001_dc11-page-001.jpg'
      },

      psychiatrist: {
            "_id":                        3,
            "referralStatus":             "accepted",
            "patientSurname":             "Flay",
            "patientgivenName":           "Sue",
            "patientGender":              "M",
            "patientBirthDay":            12,
            "patientBirthMonth":          9,
            "patientBirthYear":           1985,
            "patientAddress":             "120, Spencer Street, Melbourne",
            "patientPostcode":            "3000",
            "patientMedicare":            "12345678901",
            "patientContactNumber":       "0412345678",
            "doctorSurname":              "Arrest",
            "doctorGivenName":            "Cardiac",
            "doctorClinic":               "Chest Pain Clinic",
            "doctorAddress":              "123, Fake street, Melbourne",
            "doctorPostcode":             "3000",
            "doctorContactNumber":        "0412345679",
            "referralAppointmentDay":     12,
            "referralAppointmentMonth":   12,
            "referralAppointmentYear":    2017,
            "referralRequestedService":   "medicationReview",
            "referralReasonForReferral":  "He is crazy",
            "referralUrgent":             false,
            "referralRuralCode":          "RA3OuterRegional", 
            "referralAppointmentDate":    "12-12-2016",
            "referralAppointmentHour":    12,
            "referralAppointmentMinute":  30,
            "referralAppointmentPeriod":  "PM",
            "role":                       "admin",     
            imgProfile:                   'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/10/Crystal_Maiden.png?version=536fc77ea73fa5f2dc01a0036d199d52'
      }
}