module.exports = {
      triage: {
            "email"             :  "triage@triage.com",
            "surname"           :  "Greg",
            "giveName"          :  "Sam",
            "dateOfBirthDay"    :  "26",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              :  "triage"
      },

      gp1: {
            "email"             :  "gp@gp.com",
            "surname"           :  "Khor",
            "giveName"          :  "Ian",
            "dateOfBirthDay"    :  "30",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "gp",
      },

      gp2: {
            "email"             :  "gp2@gp2.com",
            "surname"           :  "Loong",
            "giveName"          :  "Michael",
            "dateOfBirthDay"    :  "30",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "gp",
      },

      psychiatrist1: {
            "email"             :  "psy@psy.com",
            "surname"           :  "Chen",
            "giveName"          :  "Sharon",
            "dateOfBirthDay"    :  "18",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "psychiatrist",     
      },
      psychiatrist2: {
            "email"             :  "psy2@psy2.com",
            "surname"           :  "Ward",
            "giveName"          :  "Seb",
            "dateOfBirthDay"    :  "18",
            "dateOfBirthMonth"  :  "9",
            "dateOfBirthYear"   :  "1983",
            "providerNumber"    :  "123478",
            "contactNumber"     :  "0000000",
            "primaryPlaceOfPractice" :  "Somewhere",
            "role"              : "psychiatrist",     
      }
}